--- #YAML:1.0
name:                Helix-Driver-Log-Basic
version:             0.01
abstract:            basic log driver for Helix::Framework.
license:             ~
author:              
    - Anton Belousov <abel@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Fcntl:                         0
    Helix:                         0.02
    POSIX:                         0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
